task:
  name: Test
  matrix:
    - container:
        image: debian:latest
        cpu: 1
        memory: 1G
      package install script:
        - apt-get update
        - apt-get install -y golang-go
  test_script:
    - testdata/test.bash
  