task:
  name: Test
  container:
    image: debian:latest
    cpu: 1
    memory: 1G
  install script:
    - apt-get update
    - apt-get install -y golang-go
    - apt-get install -y git
  test_script:
    - testdata/test.bash
  